policy:
  approval:
    - and:
      - peer_review

approval_rules:
  - name: peer_review
    requires:
      count: 1
      organizations: ["ContextLogic"]
    options:
      ignore_update_merges: true
