policy:
  approval:
    - and
      - peer_review

approval_rules:
  - name: peer_review
    requires:
      count: 1
      organizations: ["ContextLogic"]
    options:
      invalidate_on_push: true
      ignore_update_merges: true
