export const TableColumns = [
  "created",
  "creator",
  "lastUpdated",
  "merchantName",
  "merchantId",
  "infractionId",
  "reason",
  "parentCategory",
  "subCategory",
  "bdRep",
  "geo",
  "wssTier",
  "wssImpact",
  "correspondenceStatus",
] as const;
